name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.1.1
  esc_pos_utils: 
    git: 
      url: https://github.com/Ayeni-yeniyan/esc_pos_utils.git
      ref: master
    
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^4.0.02

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
